services:
  spark:
    version: 3.5.1
    download-source: "s3://utfsm-inf356-releases/spark-3.5.1/"
  hdfs:
    version: 3.3.6
    download-source: "s3://utfsm-inf356-releases/hadoop-3.3.6/"

provider: ec2

providers:
  ec2:
    key-name: flintrock-sa-east-1
    identity-file: flintrock-sa-east-1.pem
    instance-type: t3.small
    region: sa-east-1
    ami: ami-008609d8cd0b79ced
    user: ec2-user
    instance-profile-name: flintrock
    tenancy: default
    ebs-optimized: yes
    instance-initiated-shutdown-behavior: terminate
    # user-data: /path/to/userdata/script
    # authorize-access-from:
    #   - 10.0.0.42/32
    #   - sg-xyz4654564xyz

launch:
  num-slaves: 4
  install-hdfs: True
  install-spark: True
  # java-version: 8

debug: true