services:
  spark:
    version: 3.5.1
    download-source: "s3://utfsm-inf356-releases/spark-3.5.1/"

provider: ec2

providers:
  ec2:
    key-name: flintrock-sa-east-1
    identity-file: keys/flintrock-sa-east-1.pem
    instance-type: t2.micro
    region: sa-east-1
    ami: ami-0c89d527a4e045588
    user: ec2-user
    instance-profile-name: flintrock
    tenancy: default
    min-root-ebs-size-gb: 8
    instance-initiated-shutdown-behavior: terminate
    authorize-access-from:
      - 0.0.0.0/0

launch:
  num-slaves: 8

debug: true